### ISSUE TITLE
Wrong caret positioning after moving caret on Android

### ISSUE THREAD

**Issue by ben-su** [hodgef/react-simple-keyboard#1140]
**React-simple-keyboard version**
3.0.49

**Describe the bug**
Steps to reproduce:
- open up any simple keyboard on Mobile Android Chrome (https://hodgef.com/simple-keyboard/demos/ will do)
- write some text
- tap the text using your finger until the selection handle appears (see screenshot below)
- **drag the handle to somewhere else in the text**
- enter a character using simple-keyboard
- error: the character is inserted at the position the handle was before moving it
- expected: character appears where caret is

I debugged a bit and it turns out that the internal caret position of the keyboard does not get updated when moving around this mobile selection handle. I currently use a workaround that keeps the native `selectionStart` / `selectionEnd` in sync with the keyboard using `keyboard.setCaretPosition()`.

**Screenshots**
![image](https://user-images.githubusercontent.com/18010959/115551217-0c09ac80-a2ab-11eb-8861-916f2d9d01e9.png)

**Comment by hodgef** [comment]
Hello @ben-su,

Do you mind sharing your workaround? It will probably help in debugging this.

Regards,
Francisco Hodge

**Comment by ben-su** [comment]
Sure, I refactored it in the meantime, no interval used now:

```
// const input = nativeInputElement;

const onSelectionChanged = useCallback((): void => {
    if (
      input &&
      (keyboard.getCaretPositionStart() !== input.selectionStart ||
        keyboard.getCaretPositionEnd() !== input.selectionEnd)
    ) {
      keyboard.setCaretPosition(input.selectionStart, input.selectionEnd);
    }
  }, [input, setCaretPosition]);

 document.addEventListener('selectionchange', onSelectionChanged, true);
```

**Comment by hodgef** [comment]
Hello @ben-su,

I have added the `selectionchange` event to the list of the events that will trigger a caret position update.

The fix is available in the following versions:
- simple-keyboard@3.0.46
- **react-simple-keyboard@3.0.58**

Please feel free to update and give it a try.

Thanks!
Francisco Hodge

**Comment by by-erinmichelle** [comment]
Hi @hodgef, I'm wondering if there is a solution for this issue? I'm experiencing the same issue in Chrome on a touch screen. I'm currently using react-simple-keyboard@3.2.0. I tried using 3.0.58 with no luck. I see that you reverted the change above, is there a different release I should try? Any help is greatly appreciated, thank you!

**Comment by hodgef** [comment]
Hey @by-erinmichelle, I reverted the fix as it caused the issue https://github.com/hodgef/simple-keyboard/issues/1007. I will  implement a fix closer to Ben's workaround later today or tomorrow.

Thanks,
Francisco Hodge

**Comment by hodgef** [comment]
Hello @by-erinmichelle,

This should be fixed in react-simple-keyboard@3.2.29, feel free to give it a try.

Regards,
Francisco Hodge

**Comment by by-erinmichelle** [comment]
Hi @hodgef thank you so much for your quick response! Unfortunately, I'm still experiencing this issue in the new release. I tried to debug a bit and it looks like [this line](https://github.com/hodgef/simple-keyboard/blob/7e256907b8ace12e5b369acaa8c3a7d9a8a0a448/src/lib/components/Keyboard.ts#L1147) isn't printing after the `selectionchange` event, but I'm not sure why.

**Comment by hodgef** [comment]
Hey @by-erinmichelle,

I looked into this... and I might be crazy but `event.target` for `selectionchange` seems to be returning `document` for me instead of the input. This might be an issue worth reporting to [Chromium](https://bugs.chromium.org/p/chromium).

![image](https://user-images.githubusercontent.com/25509135/126434280-f7309340-8f9d-4c6d-a4d6-494ed3a5682b.png)
![image](https://user-images.githubusercontent.com/25509135/126434600-2e8b8884-2ba1-44ef-822f-343beb56134b.png)


I don't think I can proceed with the fix, as I need to know what's the input where the selection is being performed. The other way I can see is to attach a `selectionchange` event to every single input which is not a reasonable solution.

If you know what's your input element in advance like in @ben-su's example (https://github.com/hodgef/react-simple-keyboard/issues/1140#issuecomment-824201438), I would suggest to go with that.

Regards,
Francisco Hodge
