### ISSUE TITLE
Multiple events fired when multiple simple-keyboard instances are loaded

### ISSUE THREAD

**Issue by spemmons** [hodgef/react-simple-keyboard#34]
**react-simple-keyboard version**
1.9.1

**Describe the bug**
While investigating issue #37 I introduced some console logging of events in my local code snapshot.

What I found is that the caret event handler is being called for previous instances of the Keyboard that were instantiated in other "render" methods for other components.

In other words, if over time I have conditionally rendered N instances of the keyboard, I get N console logs for the same Touch or Mouse Event with each click of the mouse.

Oddly, however, turning "debug" on for the Keyboard shows that only the most recent instance of the Keyboard processing the event, since only 1 set debug output is logged, even though there are N copies of my console.log statement in the "caret event handler" (for example).

**Comment by hodgef** [comment]
Actually, I think the error you're describing is exactly the one fixed by 1.12.0
https://github.com/hodgef/react-simple-keyboard/releases/tag/1.12.0

Sorry, I wish I had caught this earlier! Let me know if the instructions in the above post fixes it. If not, I will re-open this issue and look into this further.

Regards

**Comment by spemmons** [comment]
I upgraded to 1.12.0, re-introduced my console logging, and i'm still seeing the problem.

**Comment by hodgef** [comment]
Hello @spemmons,

I set up [this sandbox](https://codesandbox.io/s/w2z8mjx167) and was able to reproduce the duplicated logs you describe.

I'm not sure I would file it as a bug, since it's through these events that each instance [updates its internal cursor position](https://github.com/hodgef/simple-keyboard/blob/master/src/lib/components/Keyboard.js#L539). If I didn't do this, the other instances would enter text in the wrong position.

I will consider this an enhancement request, and bind this event only once. The idea would be making the first instance that sets the event update all other instances (through the [dispatch](https://franciscohodge.com/projects/simple-keyboard/documentation/#dispatch) feature).

Stay tuned for updates regarding this.

Francisco Hodge

**Comment by spemmons** [comment]
Many thanks!
