### ISSUE TITLE
Keyboard caretPosition is not updated after clearInput

### ISSUE THREAD

**Issue by gd-ldj** [hodgef/react-simple-keyboard#46]
**React-simple-keyboard version**

"react-simple-keyboard": "1.21.2"

**Describe the bug**

Keyboard caretPosition is not updated after clearInput.
And after that, backspace does not trigger change and cannot be deleted.
![image](https://user-images.githubusercontent.com/34954129/56128955-a5fb3800-5fb3-11e9-8a51-c9fe8c68d59a.png)

**Comment by hodgef** [comment]
Hello @gd-ldj,

Thank you for reporting this issue. It should be fixed shortly.

Regards,
Francisco Hodge

**Comment by hodgef** [comment]
Hello @gd-ldj,

This issue should be fixed as of react-simple-keyboard@1.21.6 and simple-keyboard 2.20.6. Feel free to update and try it out.

Regards,
Francisco Hodge

**Comment by gd-ldj** [comment]
Thank you.
But,I still have a problem. 
When I set this.keyboardRef.keyboard.setInput("test");, the caretPosition starts to calculate on the last value. 
After using setInput, I don't know how to handle caretPosition. Can I set the value of caretPosition?

![image](https://user-images.githubusercontent.com/34954129/56190589-1b6f1300-605d-11e9-9778-96e795fe5765.png)

**Comment by hodgef** [comment]
Hello @gd-ldj ,

Indeed, you can set the internal caret position. For example:

`this.keyboardRef.keyboard.caretPosition = 0`

Regards,
Francisco Hodge

**Comment by gd-ldj** [comment]
Thank you. I get.
