### ISSUE TITLE
[typescript] KeyboardOptions type not exported

### ISSUE THREAD

**Issue by bradleygore** [hodgef/react-simple-keyboard#634]
**Is your feature request related to a problem? Please describe.**
The `KeyboardOptions` interface is not exported in the type file. This makes it very difficult to write custom keyboard components that need to extend those options in their props.

**Describe the solution you'd like**

Here is an explanation of an ideal use-case if the `KeyboardOptions` were accessible:

```
//MySpecialKB.ts

import ReactKeyboard, { KeyboardOptions } from 'react-simple-keyboard';

//custom props can extend default options interface, omitting anything as necessary, etc...
interface KBProps extends Omit<KeyboardOptions, 'layout'> {
  //custom props here
} 

cont MySpecialKB: React.FC<KBProps> = (props, ref) => {
  //use custom props to determine whatever needed...

  //finally render component
  return <ReactKeyboard {...finalProps} ref={ref} />;
};

export {KBProps};
export default React.forwardRef(MySpecialKB);
```

**Comment by bradleygore** [comment]
There is a way to do this even without it being exported, but it'd be nice to have it exported I think. Here's the way to do it without:

```
interface KBOpts extends React.ComponentPropsWithRef<typeof KeyboardReact> {
  
}
```

**Comment by hodgef** [comment]
Hello @bradleygore, thanks for reporting this!

This should be fixed now. Feel free to upgrade to latest and check it out.

Regards,
Francisco Hodge

**Comment by diogolessa** [comment]
Hi, @hodgef 

I am using the version `2.3.82`, but still unable to import the `KeyboardOptions`. I've seen that it is now being exported, but I keep getting this message:

`Module '"react-simple-keyboard"' has no exported member 'KeyboardOptions'. Did you mean to use 'import KeyboardOptions from "react-simple-keyboard"' instead? ts(2614)`

This is the code:
![image](https://user-images.githubusercontent.com/5168901/86281217-9285be00-bbb3-11ea-9149-5035ea64fb08.png)

Thanks,

**Comment by hodgef** [comment]
Hello @diogolessa, I can't seem to reproduce your issue in the following sandbox:
https://codesandbox.io/s/floral-https-d0w6m?file=/src/KeyboardWrapper.tsx

If you can provide a demo repo where you see the issue, that'll help in debugging this.

Regards,
Francisco Hodge

**Comment by diogolessa** [comment]
Thanks for the quick reply.. Well, weird then... I'll give a try on a clean repo later on, to see what differs.

Thanks, @hodgef
